// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aqua/liquidity": {
            "post": {
                "description": "Connects lender liquidity through 1inch Aqua",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aqua"
                ],
                "summary": "Connect liquidity",
                "parameters": [
                    {
                        "description": "Liquidity data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/aqua.ConnectLiquidityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/aqua/liquidity/{address}": {
            "get": {
                "description": "Returns available liquidity for a lender",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aqua"
                ],
                "summary": "Get liquidity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lender address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/aqua/withdraw": {
            "post": {
                "description": "Withdraws liquidity from Aqua",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aqua"
                ],
                "summary": "Withdraw liquidity",
                "parameters": [
                    {
                        "description": "Withdrawal data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/aqua.WithdrawLiquidityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auction": {
            "post": {
                "description": "Creates a new auction for financing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auction"
                ],
                "summary": "Create auction",
                "parameters": [
                    {
                        "description": "Auction data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auction.CreateAuctionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auction/{id}/bid": {
            "post": {
                "description": "Places a bid on a specific auction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auction"
                ],
                "summary": "Place bid",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Auction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Bid data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auction.BidRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auction/{id}/finalize": {
            "post": {
                "description": "Finalizes an auction by selecting the best bid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auction"
                ],
                "summary": "Finalize auction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Auction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rfq": {
            "get": {
                "description": "Returns a list of all RFQ requests with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RFQ"
                ],
                "summary": "List RFQs",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Record limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repositories.RFQModel"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new Request for Quote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RFQ"
                ],
                "summary": "Create RFQ",
                "parameters": [
                    {
                        "description": "RFQ data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rfq.CreateRFQRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/repositories.RFQModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rfq/{id}": {
            "get": {
                "description": "Returns information about a specific RFQ request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RFQ"
                ],
                "summary": "Get RFQ",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "RFQ ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/repositories.RFQModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rfq/{id}/quote": {
            "post": {
                "description": "Submits a quote for a specific RFQ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RFQ"
                ],
                "summary": "Submit quote",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "RFQ ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quote data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rfq.QuoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "aqua.ConnectLiquidityRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "lender_address": {
                    "type": "string"
                },
                "token_address": {
                    "type": "string"
                }
            }
        },
        "aqua.WithdrawLiquidityRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "lender_address": {
                    "type": "string"
                }
            }
        },
        "auction.BidRequest": {
            "type": "object",
            "properties": {
                "auction_id": {
                    "type": "integer"
                },
                "lender_address": {
                    "type": "string"
                },
                "limit": {
                    "type": "string"
                },
                "rate_bps": {
                    "type": "integer"
                }
            }
        },
        "auction.CreateAuctionRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "bidding_duration": {
                    "type": "integer"
                },
                "borrower_address": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                }
            }
        },
        "repositories.RFQModel": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "borrowerAddress": {
                    "type": "string"
                },
                "collateralType": {
                    "type": "integer",
                    "format": "int32"
                },
                "createdAt": {
                    "type": "integer",
                    "format": "int64"
                },
                "duration": {
                    "type": "integer",
                    "format": "int64"
                },
                "flowDescription": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "rfq.CreateRFQRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "borrower_address": {
                    "type": "string"
                },
                "collateral_type": {
                    "type": "integer"
                },
                "duration": {
                    "type": "integer"
                },
                "flow_description": {
                    "type": "string"
                }
            }
        },
        "rfq.QuoteRequest": {
            "type": "object",
            "properties": {
                "collateral_required": {
                    "type": "string"
                },
                "lender_address": {
                    "type": "string"
                },
                "limit": {
                    "type": "string"
                },
                "rate_bps": {
                    "type": "integer"
                },
                "rfq_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Aqua x402 Finance Layer API",
	Description:      "API for agent financing layer on top of the 402 protocol (x402/A2A) with 1inch Aqua integration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
